#!/usr/bin/env python3
"""
Was It The Agent? — tell whether each line of a file was written by a
human or an AI coding agent, with a confidence label.

Usage:
    wita.py <file>                 # annotate a file
    wita.py <file> --summary       # just print the human/agent ratio
    wita.py <file> --only agent    # show only agent-authored lines
    wita.py <file> --no-color      # plain output

It works by running `git blame`, then inspecting each blame commit for
agent fingerprints: co-author trailers, author/committer identities, and
generator footers that the common coding agents leave behind.
"""

import argparse
import re
import subprocess
import sys
from collections import defaultdict

# ---------------------------------------------------------------------------
# Agent fingerprints. Each entry: (label, weight, compiled regex).
# Higher weight = stronger evidence. We match against the full commit blob
# (author + committer + message + trailers), lowercased.
# ---------------------------------------------------------------------------
SIGNATURES = [
    ("Claude Code",  0.95, r"co-authored-by:\s*claude"),
    ("Claude Code",  0.95, r"generated with \[?claude code"),
    ("Claude Code",  0.70, r"noreply@anthropic\.com"),
    ("GitHub Copilot", 0.95, r"co-authored-by:\s*copilot"),
    ("GitHub Copilot", 0.80, r"copilot-swe-agent"),
    ("Cursor",       0.90, r"co-authored-by:\s*cursor"),
    ("Cursor",       0.75, r"cursoragent|cursor\.com"),
    ("Codex",        0.90, r"co-authored-by:\s*(openai )?codex"),
    ("Codex",        0.70, r"chatgpt\.com/codex"),
    ("Devin",        0.90, r"co-authored-by:\s*devin"),
    ("Aider",        0.85, r"\baider\b.*\(aider\)"),
    ("Generic bot",  0.55, r"\[bot\]|bot@users\.noreply"),
    ("Generic AI",   0.45, r"🤖|generated by ai|ai[- ]generated"),
]
SIGNATURES = [(label, w, re.compile(rx)) for (label, w, rx) in SIGNATURES]

GIT_NULL = "0000000000000000000000000000000000000000"


class Color:
    RESET = "\033[0m"
    DIM = "\033[2m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    CYAN = "\033[36m"

    @classmethod
    def off(cls):
        for k in dir(cls):
            if k.isupper():
                setattr(cls, k, "")


def run_git(args):
    return subprocess.run(
        ["git"] + args,
        capture_output=True, text=True
    )


def ensure_repo():
    r = run_git(["rev-parse", "--is-inside-work-tree"])
    if r.returncode != 0:
        sys.exit("error: not inside a git repository.")


def blame(path):
    """Return list of (commit_hash, line_text) via porcelain blame."""
    r = run_git(["blame", "--line-porcelain", "--", path])
    if r.returncode != 0:
        sys.exit(f"error: git blame failed:\n{r.stderr.strip()}")

    lines = []
    current_hash = None
    for raw in r.stdout.split("\n"):
        if not raw:
            continue
        # A header line starts with a 40-char hash followed by line numbers.
        m = re.match(r"^([0-9a-f]{40}) ", raw)
        if m and current_hash is None:
            current_hash = m.group(1)
        elif raw.startswith("\t"):
            lines.append((current_hash, raw[1:]))  # strip leading tab
            current_hash = None
    return lines


_commit_cache = {}


def classify_commit(commit_hash):
    """Return (label, confidence) for a commit. Cached."""
    if commit_hash in _commit_cache:
        return _commit_cache[commit_hash]

    if commit_hash is None or commit_hash == GIT_NULL:
        result = ("Uncommitted", 0.0)
        _commit_cache[commit_hash] = result
        return result

    r = run_git([
        "show", "-s",
        "--format=%an%n%ae%n%cn%n%ce%n%B%n%(trailers)",
        commit_hash,
    ])
    blob = r.stdout.lower()

    best_label, best_conf = "Human", 0.0
    for label, weight, rx in SIGNATURES:
        if rx.search(blob) and weight > best_conf:
            best_label, best_conf = label, weight

    result = (best_label, best_conf)
    _commit_cache[commit_hash] = result
    return result


def confidence_word(conf):
    if conf >= 0.85:
        return "high"
    if conf >= 0.6:
        return "medium"
    if conf > 0:
        return "low"
    return "-"


def verdict(conf):
    if conf == 0.0:
        return "HUMAN"
    if conf >= 0.6:
        return "AGENT"
    return "MAYBE"


def annotate(path, args):
    rows = blame(path)
    if not rows:
        sys.exit(f"error: no blame output for {path} (untracked?).")

    counts = defaultdict(int)
    agent_breakdown = defaultdict(int)

    width = len(str(len(rows)))
    out = []
    for i, (h, text) in enumerate(rows, 1):
        label, conf = classify_commit(h)
        v = verdict(conf)
        counts[v] += 1
        if v == "AGENT":
            agent_breakdown[label] += 1

        if args.only and v.lower() != args.only.lower():
            continue

        if v == "AGENT":
            tag_color = Color.YELLOW
        elif v == "HUMAN":
            tag_color = Color.GREEN
        else:
            tag_color = Color.CYAN

        tag = f"{tag_color}{v:5}{Color.RESET}"
        meta = f"{Color.DIM}{label} ({confidence_word(conf)}){Color.RESET}"
        out.append(f"{Color.DIM}{i:>{width}}{Color.RESET} {tag} {meta}  {text}")

    if not args.summary:
        print("\n".join(out))
        print()

    total = sum(counts.values())
    agent = counts["AGENT"]
    human = counts["HUMAN"]
    maybe = counts["MAYBE"]
    pct = (agent / total * 100) if total else 0

    print(f"{Color.CYAN}── Was It The Agent? ──{Color.RESET}")
    print(f"  file:   {path}")
    print(f"  lines:  {total}")
    print(f"  {Color.YELLOW}agent:  {agent} ({pct:.0f}%){Color.RESET}")
    print(f"  {Color.GREEN}human:  {human}{Color.RESET}")
    if maybe:
        print(f"  {Color.CYAN}maybe:  {maybe}{Color.RESET}")
    if agent_breakdown:
        parts = ", ".join(
            f"{k}: {v}" for k, v in sorted(
                agent_breakdown.items(), key=lambda x: -x[1])
        )
        print(f"  by agent: {parts}")

    verdict_line = (
        "the agents have been busy." if pct >= 50
        else "still mostly human hands here." if pct > 0
        else "no agent fingerprints found. suspiciously human."
    )
    print(f"\n  verdict: {verdict_line}")


def main():
    p = argparse.ArgumentParser(
        description="Tell whether each line was written by a human or an AI agent.")
    p.add_argument("file", help="path to a git-tracked file")
    p.add_argument("--summary", action="store_true",
                   help="print only the summary, not per-line annotations")
    p.add_argument("--only", choices=["agent", "human", "maybe"],
                   help="show only lines of this verdict")
    p.add_argument("--no-color", action="store_true", help="disable colors")
    args = p.parse_args()

    if args.no_color or not sys.stdout.isatty():
        Color.off()

    ensure_repo()
    annotate(args.file, args)


if __name__ == "__main__":
    main()
