name: Security scan

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: bandit -r wita.py wita/ -ll
